### ISSUE TITLE
E254: Cannot allocate color none

### ISSUE THREAD

**Issue by Blake-LeBlanc** [aditya-azad/candle-grey#1]
Hello Aditya!

Whenever I load the colorscheme, I receive the following error message:

```
Error detected while processing /home/linux/.vim/plugged/candle-grey/colors/candle-grey.vim:
line   33:
E254: Cannot allocate color none
```
From what I can tell comparing to your screenshots, most (all?) of the colorscheme displays properly.

Is there anything I can do to remedy the error message on my end?

All the best,
Blake

**Comment by aditya-azad** [comment]
Hello,

I have changed the lower case none to NONE. It seems like this is what was causing problems to some users. Please pull the changes and let me know if it is working now or not.

Thanks!

**Comment by Blake-LeBlanc** [comment]
Was able to test it this morning and yes, that fixed the issue!

Thank you Aditya!
